machineA:
  cpu_cores: 8
  ram_gb: 64
  gpus: 1
  nvme_count: 2
  has_ext_sr: false
  arm: false
  gpu_models:
    - "NVIDIA RTX 4070 Ti Super"
  gpu_vram_gb:
    - 16

machineB:
  cpu_cores: 16
  ram_gb: 64
  gpus: 2
  nvme_count: 2
  has_ext_sr: false
  arm: false
  gpu_models:
    - "NVIDIA RTX 5060 Ti"
    - "NVIDIA RTX 5060 Ti"
  gpu_vram_gb:
    - 16
    - 16

machineC:
  cpu_cores: 12
  ram_gb: 32
  gpus: 1
  nvme_count: 2
  has_ext_sr: true
  arm: false
  gpu_models:
    - "NVIDIA RTX 2070 Ti Super"
  gpu_vram_gb:
    - 8

machineD:
  cpu_cores: 12
  ram_gb: 64
  gpus: 1
  nvme_count: 0
  has_ext_sr: false
  arm: false
  gpu_models:
    - "Intel Arc B580"
  gpu_vram_gb:
    - 16

machineE:
  cpu_cores: 8
  ram_gb: 16
  gpus: 0
  nvme_count: 0
  has_ext_sr: false
  arm: false

machineF:
  cpu_cores: 0
  ram_gb: 0
  gpus: 0
  nvme_count: 0
  has_ext_sr: false
  arm: false

machinePi4:
  cpu_cores: 4
  ram_gb: 4
  gpus: 0
  nvme_count: 0
  has_ext_sr: false
  arm: true

machineARM:
  cpu_cores: 0
  ram_gb: 0
  gpus: 0
  nvme_count: 0
  has_ext_sr: false
  arm: true
